### ISSUE TITLE
Comments should be gray instead of blue

### ISSUE THREAD

**Issue by Saafo** [catppuccin/xcode#3]
I'm also using `catppuccin latte` in nvim and VSCode, and the comment in both are gray, but in xcode it's blue. It's kind of weird.

**Comment by quentinguidee** [comment]
Thanks for this issue! I agree that this needs to be fixed.

That said more generally, Xcode has very different settings than those available on VSCode, so it is possible that other inconsistencies compared to VSCode (or JetBrains) colorschemes are not adjustable.
